site_name: Ansari Documentation
site_url: https://docs.ansari.chat
nav:
  - Home: index.md
  - What Ansari can do: capabilities.md
  - Validation: validation.md
  - FAQ: faq.md
  - Additional material: material.md
  - Privacy policy: privacy.md
  - Terms of service: terms.md
  - Support: support.md

theme: readthedocs

extra_css:
  - css/extra.css

