site_name: Ansari
site_url: https://beta.ansari.chat/docs
nav:
  - Home: index.md
  - What Ansari can do: capabilities.md
  - Validation: validation.md
  - FAQ: faq.md
  - Additional material: material.md
  - Privacy policy: privacy.md
  - Terms of service: terms.md

theme: readthedocs

